(()=>{'use strict';
const fmt=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const STORAGE_KEY='derGrosseCoupSaveV022';
const crew=window.GAME_CREW,tools=window.GAME_TOOLS,cars=window.GAME_CARS,missions=window.GAME_MISSIONS;
let state=defaultState(),currentMission=null,selectedCrewId='emil';
let sim={timer:null,running:false,paused:false,time:0,maxTime:0,events:[],eventIndex:0,analysis:null,positions:{},speed:4,failed:false};
function defaultState(){return{version:22,money:10000,heat:0,completed:[false,false],currentMission:0,plans:{},selectedCrew:['emil','bruno','rudi'],tool:'basic',car:'compact'}}
function $(id){return document.getElementById(id)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state={...defaultState(),...JSON.parse(raw)}}catch(e){console.warn(e)}$('continueBtn').disabled=!localStorage.getItem(STORAGE_KEY)}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0)}
function newGame(){state=defaultState();save();showHQ()} function continueGame(){load();showHQ()}
function stopTimer(){if(sim.timer){clearInterval(sim.timer);sim.timer=null}}
function showHQ(){stopTimer();renderHQ();showScreen('hq')}
function renderHQ(){$('money').textContent=fmt.format(state.money);$('heat').textContent=`${state.heat}/5`;$('missionList').innerHTML=missions.map((m,i)=>{const locked=i>0&&!state.completed[i-1],done=state.completed[i];return `<article class="mission-card ${locked?'locked':''}"><div class="row"><div class="grow"><div class="eyebrow">MISSION ${i+1}</div><h3>${m.shortTitle}</h3><p>${m.desc}</p><span class="badge">Beute ${fmt.format(m.reward)}</span><span class="badge">Mindestteam ${m.minCrew}</span>${done?'<span class="badge">ABGESCHLOSSEN</span>':''}</div><button ${locked?'disabled':''} data-plan="${i}">${done?'Erneut planen':'Planung öffnen'}</button></div></article>`}).join('');document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openPlanning(Number(b.dataset.plan)))}
function getPlan(){const id=String(currentMission.id);if(!state.plans[id])state.plans[id]={routes:{},waits:{},godMode:false};const p=state.plans[id];p.waits=p.waits||{};return p}
function openPlanning(index){stopTimer();currentMission=missions[index];state.currentMission=index;const plan=getPlan();selectedCrewId=state.selectedCrew.find(id=>crew.some(c=>c.id===id))||'emil';$('planTitle').textContent=currentMission.title;$('planDesc').textContent=currentMission.desc;$('budget').textContent=fmt.format(state.money);populateEquipment();renderCrew();renderMissionInfo();$('godModeToggle').checked=!!plan.godMode;renderMap();renderTimeline();updateCost();updatePlanStatus('Ungeprüft');$('godReport').textContent='Noch keine Prüfung durchgeführt.';$('godReport').className='god-report';showScreen('planning')}
function populateEquipment(){$('toolSelect').innerHTML=tools.map(t=>`<option value="${t.id}" ${state.tool===t.id?'selected':''}>${t.name} · ${fmt.format(t.cost)}</option>`).join('');$('carSelect').innerHTML=cars.map(c=>`<option value="${c.id}" ${state.car===c.id?'selected':''}>${c.name} · ${fmt.format(c.cost)}</option>`).join('')}
function renderCrew(){const p=getPlan();$('crewList').innerHTML=crew.map(c=>{const selected=state.selectedCrew.includes(c.id),count=(p.routes[c.id]||[]).length,w=(p.waits[c.id]||[]).reduce((a,b)=>a+b.seconds,0);return `<div class="crew-card ${selected?'':'unselected'} ${selectedCrewId===c.id?'active':''}" data-crew="${c.id}" style="--member-color:${c.color}"><div class="crew-token">${c.short}</div><div><div class="crew-name">${c.name}</div><div class="crew-role">${c.role} · ${count} Punkte${w?` · ${w}s Warten`:''}</div></div><input class="crew-check" type="checkbox" ${selected?'checked':''}></div>`}).join('');document.querySelectorAll('.crew-card').forEach(card=>card.onclick=e=>{const id=card.dataset.crew;if(e.target.matches('input')){toggleCrew(id,e.target.checked);e.stopPropagation();return}if(!state.selectedCrew.includes(id))toggleCrew(id,true);selectedCrewId=id;renderCrew();renderMap();renderTimeline()})}
function toggleCrew(id,on){const p=getPlan();if(on&&!state.selectedCrew.includes(id))state.selectedCrew.push(id);if(!on){state.selectedCrew=state.selectedCrew.filter(x=>x!==id);delete p.routes[id];delete p.waits[id];selectedCrewId=state.selectedCrew[0]||crew[0].id}save();renderCrew();renderMap();renderTimeline();updateCost()}
function renderMissionInfo(){$('missionInfo').innerHTML=`<div class="info-list">${Object.entries(currentMission.intel).map(([k,v])=>`<span>${k}</span><strong>${v}</strong>`).join('')}</div><p class="small">Ziele: ${currentMission.objectiveNodes.map(id=>nodeById(id).label).join(', ')}</p>`}
function nodeById(id){return currentMission.nodes.find(n=>n.id===id)} function connected(a,b){return currentMission.edges.some(e=>(e[0]===a&&e[1]===b)||(e[0]===b&&e[1]===a))}
function svgAdd(svg,tag,attrs,parent=svg){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs||{}).forEach(([k,v])=>el.setAttribute(k,v));parent.appendChild(el);return el}
function drawGroupMarker(svg,x,y,ids){const n=ids.length,r=18;if(n===1){const c=crew.find(z=>z.id===ids[0]);svgAdd(svg,'circle',{cx:x,cy:y,r,fill:c.color,stroke:'#080a08','stroke-width':5});const t=svgAdd(svg,'text',{x,y:y+6,fill:'#fff','font-size':15,'font-weight':'bold','text-anchor':'middle'});t.textContent=c.short;return}ids.forEach((id,i)=>{const c=crew.find(z=>z.id===id),a0=(i/n)*Math.PI*2-Math.PI/2,a1=((i+1)/n)*Math.PI*2-Math.PI/2;const x0=x+r*Math.cos(a0),y0=y+r*Math.sin(a0),x1=x+r*Math.cos(a1),y1=y+r*Math.sin(a1),large=(a1-a0)>Math.PI?1:0;svgAdd(svg,'path',{d:`M ${x} ${y} L ${x0} ${y0} A ${r} ${r} 0 ${large} 1 ${x1} ${y1} Z`,fill:c.color,stroke:'#080a08','stroke-width':2})});const t=svgAdd(svg,'text',{x,y:y+5,fill:'#fff','font-size':12,'font-weight':'bold','text-anchor':'middle'});t.textContent=n}
function renderBaseMap(svg,interactive=true,positions=null){svg.innerHTML='';currentMission.rooms.forEach(r=>{svgAdd(svg,'rect',{x:r.x,y:r.y,width:r.w,height:r.h,class:r.outside?'outside-shape':'room-shape'});const t=svgAdd(svg,'text',{x:r.x+r.w/2,y:r.y+r.h/2,class:'room-label'});t.textContent=r.label});const showConn=$('showConnections')?.checked!==false||!getPlan().godMode;currentMission.edges.forEach(([a,b])=>{const na=nodeById(a),nb=nodeById(b);svgAdd(svg,'line',{x1:na.x,y1:na.y,x2:nb.x,y2:nb.y,class:`map-edge ${showConn?'':'god-hidden'}`})});const showHaz=$('showHazards')?.checked!==false&&getPlan().godMode;currentMission.hazards.forEach(h=>svgAdd(svg,'rect',{x:h.x,y:h.y,width:h.w,height:h.h,class:`hazard-zone ${showHaz?'':'hidden'}`}));renderRoutes(svg);currentMission.nodes.forEach(n=>{const g=svgAdd(svg,'g',{class:`map-node ${n.type||'normal'} ${((getPlan().routes[selectedCrewId]||[]).includes(n.id))?'selected':''}`});svgAdd(svg,'circle',{cx:n.x,cy:n.y,r:22},g);const txt=svgAdd(svg,'text',{x:n.x,y:n.y},g);txt.textContent=n.objective?'★':n.type==='exit'?'F':n.type==='hazard'?'!':'•';const lab=svgAdd(svg,'text',{x:n.x,y:n.y+42,class:'node-label'},g);lab.textContent=n.label;if(interactive){g.addEventListener('click',()=>addWaypoint(n.id));g.addEventListener('touchend',ev=>{ev.preventDefault();addWaypoint(n.id)},{passive:false})}});if(positions){const groups={};Object.entries(positions).forEach(([id,pos])=>{const key=`${Math.round(pos.x)}:${Math.round(pos.y)}`;(groups[key] ||= {x:pos.x,y:pos.y,ids:[]}).ids.push(id)});Object.values(groups).forEach(g=>drawGroupMarker(svg,g.x,g.y,g.ids))}}
function renderRoutes(svg){const p=getPlan();crew.forEach(c=>{const route=p.routes[c.id]||[],pts=route.map(nodeById).filter(Boolean);if(pts.length>1)svgAdd(svg,'polyline',{points:pts.map(q=>`${q.x},${q.y}`).join(' '),class:'route-line',stroke:c.color});pts.forEach((q,i)=>{svgAdd(svg,'circle',{cx:q.x,cy:q.y,r:13,fill:c.color,class:'route-marker'});const t=svgAdd(svg,'text',{x:q.x,y:q.y,class:'route-number'});t.textContent=i+1})})}
function renderMap(){renderBaseMap($('missionMap'),true);const c=crew.find(x=>x.id===selectedCrewId),r=getPlan().routes[selectedCrewId]||[];$('mapHint').textContent=c?`${c.name}: ${r.length?`Nächster verbundener Punkt nach ${nodeById(r.at(-1)).label}.`:'Startpunkt wählen.'}`:'Wähle ein Teammitglied.'}
function addWaypoint(id){if(!state.selectedCrew.includes(selectedCrewId))return;const p=getPlan(),r=p.routes[selectedCrewId]||(p.routes[selectedCrewId]=[]);if(r.length&&r.at(-1)===id)return;if(r.length&&!connected(r.at(-1),id)){$('mapHint').textContent='Punkt nicht direkt verbunden.';return}r.push(id);save();renderMap();renderTimeline();updatePlanStatus('Geändert')}
function addWait(){const p=getPlan(),r=p.routes[selectedCrewId]||[];if(!r.length){$('mapHint').textContent='Zuerst einen Standort planen.';return}const arr=p.waits[selectedCrewId]||(p.waits[selectedCrewId]=[]),afterIndex=r.length-1,seconds=Number($('waitSeconds').value);arr.push({afterIndex,seconds});save();renderCrew();renderTimeline();updatePlanStatus('Geändert');$('mapHint').textContent=`${seconds} Sekunden Warten nach ${nodeById(r.at(-1)).label} eingefügt.`}
function undoWaypoint(){const p=getPlan(),r=p.routes[selectedCrewId]||[];r.pop();p.waits[selectedCrewId]=(p.waits[selectedCrewId]||[]).filter(w=>w.afterIndex<r.length);save();renderCrew();renderMap();renderTimeline()}
function clearRoute(){const p=getPlan();p.routes[selectedCrewId]=[];p.waits[selectedCrewId]=[];save();renderCrew();renderMap();renderTimeline()} function clearAllRoutes(){const p=getPlan();p.routes={};p.waits={};save();renderCrew();renderMap();renderTimeline()}
function actionDuration(c,node,prev){let d=node.duration||15;if(node.requires===c.bonus)d=Math.max(12,Math.round(d*.62));if(prev)d+=Math.max(5,Math.round(Math.hypot(node.x-prev.x,node.y-prev.y)/14));return d}
function routeActions(c,route){const waits=getPlan().waits[c.id]||[];let time=0,out=[];route.forEach((id,i)=>{const n=nodeById(id),prev=i?nodeById(route[i-1]):null,d=i===0?0:actionDuration(c,n,prev),start=time;time+=d;out.push({node:n,start,duration:d,end:time,action:i===0?'Position beziehen':(n.action||`Zu ${n.label} bewegen`),kind:i===0?'start':'action'});waits.filter(w=>w.afterIndex===i).forEach(w=>{const s=time;time+=w.seconds;out.push({node:n,start:s,duration:w.seconds,end:time,action:`Warten (${w.seconds}s)`,kind:'wait'})})});return out}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function renderTimeline(){let max=0;$('timelineGrid').innerHTML=state.selectedCrew.map(id=>{const c=crew.find(x=>x.id===id),a=routeActions(c,getPlan().routes[id]||[]);max=Math.max(max,a.at(-1)?.end||0);return `<div class="timeline-row"><div class="timeline-person"><span class="crew-token" style="--member-color:${c.color};border-color:${c.color};color:${c.color}">${c.short}</span><div>${c.name.split(' „')[0]}<div class="crew-role">${c.role}</div></div></div><div class="timeline-track">${a.length?a.map(x=>`<div class="time-block ${x.kind==='wait'?'wait-block':''}" style="background:${x.kind==='wait'?'rgba(225,200,77,.18)':c.color+'33'};flex:${Math.max(1,x.duration)}"><strong>${formatTime(x.start)}</strong>${x.action}<small>${x.duration}s</small></div>`).join(''):'<div class="empty-plan">Noch keine Route.</div>'}</div></div>`}).join('');$('planDuration').textContent=formatTime(max)}
function updateCost(){state.tool=$('toolSelect').value;state.car=$('carSelect').value;const cc=state.selectedCrew.reduce((s,id)=>s+(crew.find(c=>c.id===id)?.cost||0),0),t=tools.find(x=>x.id===state.tool),car=cars.find(x=>x.id===state.car),sum=cc+(t?.cost||0)+(car?.cost||0);$('costSummary').innerHTML=`Team ${fmt.format(cc)}<br>Werkzeug ${fmt.format(t?.cost||0)}<br>Fahrzeug ${fmt.format(car?.cost||0)}<hr>Gesamt <strong>${fmt.format(sum)}</strong>`;save()}
function updatePlanStatus(t){$('planStatus').textContent=t}
function autoPlan(){const p=getPlan();p.routes=JSON.parse(JSON.stringify(currentMission.recommended));p.waits={};if(currentMission.id===1)p.waits.klara=[{afterIndex:1,seconds:10}];state.selectedCrew=Object.keys(currentMission.recommended);save();renderCrew();renderMap();renderTimeline();updateCost();updatePlanStatus('Musterplan')}
function intervalsOverlap(a,b){return a.start<b.end&&b.start<a.end}
function analyze(){const p=getPlan(),issues=[],warnings=[];let maxTime=0;const actionsBy={};if(state.selectedCrew.length<currentMission.minCrew)issues.push(`Mindestens ${currentMission.minCrew} Teammitglieder erforderlich.`);currentMission.requiredBonuses.forEach(b=>{if(!state.selectedCrew.some(id=>crew.find(c=>c.id===id)?.bonus===b))issues.push(`Spezialist fehlt: ${b==='locks'?'Schlossknacker':'Elektronikerin'}.`)});const visited=new Set();state.selectedCrew.forEach(id=>{const c=crew.find(x=>x.id===id),r=p.routes[id]||[],acts=routeActions(c,r);actionsBy[id]=acts;maxTime=Math.max(maxTime,acts.at(-1)?.end||0);r.forEach(x=>visited.add(x));if(r.length&&r[0]!==currentMission.entryNode)warnings.push(`${c.name}: Start nicht am Fluchtwagen.`);if(r.length&&r.at(-1)!==currentMission.exitNode)issues.push(`${c.name}: endet nicht am Fluchtwagen.`);acts.forEach(a=>{if(a.node.requires&&a.node.requires!==c.bonus&&a.kind==='action')warnings.push(`${c.name} ist für „${a.action}“ nicht spezialisiert.`)})});currentMission.objectiveNodes.forEach(id=>{if(!visited.has(id))issues.push(`Ziel fehlt: ${nodeById(id).label}.`)});
 const narrow=new Set(currentMission.nodes.filter(n=>/Tür|Eingang|Flur/.test(n.label)).map(n=>n.id));const all=[];Object.entries(actionsBy).forEach(([id,arr])=>arr.filter(a=>a.kind==='action').forEach(a=>all.push({...a,crewId:id})));for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const a=all[i],b=all[j];if(a.crewId!==b.crewId&&a.node.id===b.node.id&&narrow.has(a.node.id)&&intervalsOverlap(a,b))issues.push(`Stau bei ${a.node.label}: ${crew.find(c=>c.id===a.crewId).short} und ${crew.find(c=>c.id===b.crewId).short} gleichzeitig (${formatTime(Math.max(a.start,b.start))}).`)}
 if(maxTime>420)warnings.push('Plan dauert länger als sieben Minuten.');let success=Math.max(5,Math.min(96,currentMission.baseChance-issues.length*22-warnings.length*5+state.selectedCrew.reduce((s,id)=>s+crew.find(c=>c.id===id).skill,0)/4));return{valid:!issues.length,issues:[...new Set(issues)],warnings:[...new Set(warnings)],success:Math.round(success),maxTime,actionsBy}}
function simulatePlan(){const r=analyze();let text=`PLANPRÜFUNG\nERFOLGSCHANCE: ${r.success}%\nGESAMTDAUER: ${formatTime(r.maxTime)}\n\n`;if(!r.issues.length&&!r.warnings.length)text+='Keine Planungsfehler erkannt.';if(r.issues.length)text+='KRITISCHE FEHLER:\n- '+r.issues.join('\n- ')+'\n\n';if(r.warnings.length)text+='WARNUNGEN:\n- '+r.warnings.join('\n- ');$('godReport').textContent=text;$('godReport').className=`god-report ${r.valid?'ok':'fail'}`;updatePlanStatus(r.valid?'Prüfung bestanden':'Fehler im Plan');return r}
function savePlan(){save();updatePlanStatus('Gespeichert');$('mapHint').textContent='Plan lokal gespeichert.'}
function startMission(){const r=simulatePlan();if(!r.valid){$('mapHint').textContent='Kritische Fehler zuerst beheben.';return}runExecution(r)}
function buildEvents(analysis){const ev=[];Object.entries(analysis.actionsBy).forEach(([id,arr])=>{const c=crew.find(x=>x.id===id);arr.slice(1).forEach(a=>ev.push({...a,crew:c,type:'action'}))});ev.sort((a,b)=>a.end-b.end);return ev}
function positionAt(id,t){const c=crew.find(x=>x.id===id),a=routeActions(c,getPlan().routes[id]||[]);let last=a[0];for(const x of a){if(x.end<=t)last=x;else break}return last?{x:last.node.x,y:last.node.y}:null}
function updateExecution(){const positions={};state.selectedCrew.forEach(id=>{const p=positionAt(id,sim.time);if(p)positions[id]=p});sim.positions=positions;renderBaseMap($('executionMap'),false,positions);$('execClock').textContent=formatTime(sim.time);$('progressBar').style.width=`${Math.min(100,sim.time/Math.max(1,sim.maxTime)*100)}%`}
function logEvent(e){$('log').textContent+=`${formatTime(e.end)}  ${e.crew.name}: ${e.action}.\n`;$('log').scrollTop=$('log').scrollHeight}
function processEvents(){while(sim.eventIndex<sim.events.length&&sim.events[sim.eventIndex].end<=sim.time){const e=sim.events[sim.eventIndex++];logEvent(e);if(e.node.type==='hazard'&&e.node.requires&&e.crew.bonus!==e.node.requires&&!sim.failed){sim.failed=true;pauseSimulation();showEvent('Alarm ausgelöst',`${e.crew.name} hat „${e.node.label}“ ohne passenden Spezialisten erreicht. Der Ablauf wurde bei ${formatTime(e.end)} angehalten.`)}}if(sim.time>=sim.maxTime&&!sim.failed)finishMission(sim.analysis)}
function runExecution(analysis){stopTimer();sim={timer:null,running:true,paused:false,time:0,maxTime:analysis.maxTime,events:buildEvents(analysis),eventIndex:0,analysis,positions:{},speed:Number($('speedSelect')?.value||4),failed:false};showScreen('execution');$('execTitle').textContent=currentMission.title;$('alarm').textContent='0/5';$('progressBar').style.width='0%';$('log').textContent='PLAN GELADEN. EINSATZ BEGINNT.\n';$('pauseBtn').textContent='Pause';updateExecution();startTimer()}
function startTimer(){stopTimer();if(sim.paused||!sim.running)return;sim.timer=setInterval(()=>advance(1),250/Math.max(1,sim.speed))}
function advance(seconds){if(!sim.running)return;sim.time=Math.min(sim.maxTime,sim.time+seconds);updateExecution();processEvents()}
function togglePause(){if(!sim.running)return;sim.paused=!sim.paused;$('pauseBtn').textContent=sim.paused?'Fortsetzen':'Pause';sim.paused?stopTimer():startTimer()}
function pauseSimulation(){sim.paused=true;stopTimer();$('pauseBtn').textContent='Fortsetzen'}
function stepSecond(){if(!sim.running)return;pauseSimulation();advance(1)}
function stepEvent(){if(!sim.running)return;pauseSimulation();const next=sim.events[sim.eventIndex];if(next){sim.time=next.end;updateExecution();processEvents()}else advance(Math.max(0,sim.maxTime-sim.time))}
function setSpeed(){sim.speed=Number($('speedSelect').value);if(sim.running&&!sim.paused)startTimer()}
function showEvent(title,msg){$('eventTitle').textContent=title;$('eventMessage').textContent=msg;$('eventModal').classList.remove('hidden')}
function hideEvent(){$('eventModal').classList.add('hidden')}
function eventContinue(){hideEvent();sim.failed=false;sim.paused=false;$('pauseBtn').textContent='Pause';startTimer()}
function eventPlanning(){hideEvent();stopTimer();openPlanning(state.currentMission)}
function eventAbort(){hideEvent();abortMission()}
function finishMission(a){if(!sim.running)return;sim.running=false;stopTimer();const success=Math.random()*100<=a.success;if(success){state.money+=currentMission.reward;state.completed[currentMission.id]=true;state.heat=Math.min(5,state.heat+(currentMission.id?1:0));save();$('resultTitle').innerHTML='<span class="result-success">COUP GELUNGEN</span>';$('resultText').innerHTML=`<p>Plan erfolgreich ausgeführt.</p><p>Beute: <strong>${fmt.format(currentMission.reward)}</strong></p><p>Erfolgschance: ${a.success}%</p>`}else{state.heat=Math.min(5,state.heat+1);save();$('resultTitle').innerHTML='<span class="result-fail">COUP GESCHEITERT</span>';$('resultText').innerHTML='<p>Ein unvorhergesehenes Ereignis brachte den Ablauf zum Scheitern.</p>'}showScreen('result')}
function abortMission(){sim.running=false;stopTimer();$('resultTitle').innerHTML='<span class="result-fail">EINSATZ ABGEBROCHEN</span>';$('resultText').innerHTML='<p>Die Bande hat sich zurückgezogen.</p>';showScreen('result')}
function restartCurrent(){openPlanning(state.currentMission)} function setGodMode(){getPlan().godMode=$('godModeToggle').checked;save();renderMap()}
window.CoupGame={load,newGame,continueGame,showScreen,showHQ,autoPlan,startMission,abortMission,restartCurrent,undoWaypoint,clearRoute,clearAllRoutes,simulatePlan,savePlan,setGodMode,renderMap,updateCost,addWait,togglePause,stepSecond,stepEvent,setSpeed,eventContinue,eventPlanning,eventAbort};
})();
