const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const game=fs.readFileSync('game.js','utf8');
const script=fs.readFileSync('script.js','utf8');
const requiredIds=['execStartBtn','execPauseBtn','execContinueBtn','execStepBtn','execNextEventBtn','speedSelect','backToPlanningBtn','eventDialog','eventContinueBtn','eventPauseBtn','eventPlanningBtn','eventAbortBtn','execStatus'];
const requiredExports=['beginExecution','pauseExecution','continueExecution','stepExecution','nextEventExecution','acknowledgeEventAndContinue','acknowledgeEventPaused','changeExecutionSpeed','returnToPlanning'];
for(const id of requiredIds)if(!html.includes(`id="${id}"`))throw new Error(`Fehlende ID: ${id}`);
for(const name of requiredExports)if(!game.includes(name))throw new Error(`Fehlender Export: ${name}`);
if(!game.includes('renderActorMarkers'))throw new Error('Mehrpersonenmarker fehlt');
if(game.includes('Math.random'))throw new Error('Zufall ist im RC2-Kern nicht zulässig');
for(const id of requiredIds)if(!script.includes(id)&&!['eventDialog','execStatus'].includes(id))console.warn(`ID nicht direkt gebunden: ${id}`);
console.log('STATIC CHECK OK');
